
del /Q /S build\CMakeCache.txt
del /Q /S build\ExternalProjects\embree\build\CMakeCache.txt

cmake -S . -B build -G Ninja ^
-DCMAKE_BUILD_TYPE=Release ^
-DLIBIGL_BUILD_TESTS=OFF ^
-DLIBIGL_USE_STATIC_LIBRARY=OFF ^
-DLIBIGL_USE_PREBUILT_LIBRARIES=ON ^
-DLIBIGL_WITH_COMISO=OFF ^
-DLIBIGL_WITH_EMBREE=ON ^
-DLIBIGL_WITH_TETGEN=OFF ^
-DLIBIGL_WITH_TRIANGLE=OFF ^
-DLIBIGL_WITH_XML=OFF ^
-DTUTORIALS_CHAPTER1=OFF ^
-DTUTORIALS_CHAPTER2=OFF ^
-DTUTORIALS_CHAPTER3=OFF ^
-DTUTORIALS_CHAPTER4=OFF ^
-DTUTORIALS_CHAPTER5=OFF ^
-DTUTORIALS_CHAPTER6=ON ^
-DTUTORIALS_CHAPTER7=OFF

cmake --build build
