del /Q build\CMakeCache.txt

cmake -S . -B build -G Ninja ^
-DCMAKE_BUILD_TYPE=Release ^
-DLIBIGL_BUILD_TESTS=OFF ^
-DLIBIGL_USE_STATIC_LIBRARY=OFF ^
-DLIBIGL_WITH_MMG=ON ^
-DLIBMMG2D_SHARED=ON ^
-DLIBMMG2D_STATIC=OFF ^
-DLIBIGL_WITH_COMISO=OFF ^
-DLIBIGL_WITH_EMBREE=OFF ^
-DLIBIGL_WITH_TETGEN=OFF ^
-DLIBIGL_WITH_TRIANGLE=ON ^
-DLIBIGL_WITH_XML=OFF ^
-DTUTORIALS_CHAPTER1=OFF ^
-DTUTORIALS_CHAPTER2=OFF ^
-DTUTORIALS_CHAPTER3=OFF ^
-DTUTORIALS_CHAPTER4=OFF ^
-DTUTORIALS_CHAPTER5=OFF ^
-DTUTORIALS_CHAPTER6=OFF

cmake --build build
