#!/bin/bash

rm -rf build/CMakeCache.txt
rm -rf build/ExternalProjects/mmg/build/CMakeCache.txt

cmake -S . -B build -G Ninja \
-DCMAKE_BUILD_TYPE=Release \
-DLIBIGL_USE_STATIC_LIBRARY=OFF \
-DLIBIGL_BUILD_TESTS=OFF \
-DLIBIGL_WITH_OPENGL=ON \
-DLIBIGL_WITH_OPENGL_GLFW=ON \
-DLIBIGL_WITH_MMG=ON \
-DLIBIGL_BUILD_TUTORIALS=ON \
-DTUTORIALS_CHAPTER1=OFF \
-DTUTORIALS_CHAPTER2=OFF \
-DTUTORIALS_CHAPTER3=OFF \
-DTUTORIALS_CHAPTER4=OFF \
-DTUTORIALS_CHAPTER5=OFF \
-DTUTORIALS_CHAPTER6=OFF \
-DTUTORIALS_CHAPTER7=ON

cmake --build build
