#!/bin/bash

cmake -S . -B build \
-DCMAKE_BUILD_TYPE=Release \
-DLIBIGL_WITH_MMG=ON \
-DBUILD_SHARED_LIBS=ON \
-DLIBIGL_BUILD_TESTS=OFF \
-DLIBIGL_USE_STATIC_LIBRARY=OFF \
-DLIBIGL_WITH_COMISO=OFF \
-DLIBIGL_WITH_EMBREE=OFF \
-DLIBIGL_WITH_TETGEN=OFF \
-DLIBIGL_WITH_TRIANGLE=OFF \
-DLIBIGL_WITH_XML=OFF \
-DTUTORIALS_CHAPTER1=OFF \
-DTUTORIALS_CHAPTER2=OFF \
-DTUTORIALS_CHAPTER3=OFF \
-DTUTORIALS_CHAPTER4=OFF \
-DTUTORIALS_CHAPTER5=OFF \
-DTUTORIALS_CHAPTER6=OFF \
-G Ninja
