#!/bin/bash

MMG_SOURCEDIR=$1
MMG_DIR=$2
MMG_BUILDTYPE=$3

cmake -S $MMG_SOURCEDIR -B $MMG_DIR \
-DCMAKE_BUILD_TYPE=$MMG_BUILDTYPE \
-DBUILD=MMG2D \
-DBUILD_SHARED_LIBS=ON \
-DLIBMMG2D_STATIC=ON \
-DLIBMMG2D_SHARED=ON \
-DUSE_SCOTCH=OFF \
-DUSE_ELAS=OFF \
-DUSE_VTK=OFF \
-DMMG2D_CI=OFF \
-DBUILD_TESTING=OFF 

make -C $MMG_DIR
